# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nprat/Documents/OpenGL-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nprat/Documents/OpenGL-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nprat/Documents/OpenGL-Project/CMakeFiles /home/nprat/Documents/OpenGL-Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nprat/Documents/OpenGL-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGL

# Build rule for target.
OpenGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGL
.PHONY : OpenGL

# fast build rule for target.
OpenGL/fast:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/build
.PHONY : OpenGL/fast

src/Core/glapi.o: src/Core/glapi.cpp.o

.PHONY : src/Core/glapi.o

# target to build an object file
src/Core/glapi.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Core/glapi.cpp.o
.PHONY : src/Core/glapi.cpp.o

src/Core/glapi.i: src/Core/glapi.cpp.i

.PHONY : src/Core/glapi.i

# target to preprocess a source file
src/Core/glapi.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Core/glapi.cpp.i
.PHONY : src/Core/glapi.cpp.i

src/Core/glapi.s: src/Core/glapi.cpp.s

.PHONY : src/Core/glapi.s

# target to generate assembly for a file
src/Core/glapi.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Core/glapi.cpp.s
.PHONY : src/Core/glapi.cpp.s

src/Core/openGL.o: src/Core/openGL.cpp.o

.PHONY : src/Core/openGL.o

# target to build an object file
src/Core/openGL.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Core/openGL.cpp.o
.PHONY : src/Core/openGL.cpp.o

src/Core/openGL.i: src/Core/openGL.cpp.i

.PHONY : src/Core/openGL.i

# target to preprocess a source file
src/Core/openGL.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Core/openGL.cpp.i
.PHONY : src/Core/openGL.cpp.i

src/Core/openGL.s: src/Core/openGL.cpp.s

.PHONY : src/Core/openGL.s

# target to generate assembly for a file
src/Core/openGL.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Core/openGL.cpp.s
.PHONY : src/Core/openGL.cpp.s

src/Display/cameramodule.o: src/Display/cameramodule.cpp.o

.PHONY : src/Display/cameramodule.o

# target to build an object file
src/Display/cameramodule.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/cameramodule.cpp.o
.PHONY : src/Display/cameramodule.cpp.o

src/Display/cameramodule.i: src/Display/cameramodule.cpp.i

.PHONY : src/Display/cameramodule.i

# target to preprocess a source file
src/Display/cameramodule.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/cameramodule.cpp.i
.PHONY : src/Display/cameramodule.cpp.i

src/Display/cameramodule.s: src/Display/cameramodule.cpp.s

.PHONY : src/Display/cameramodule.s

# target to generate assembly for a file
src/Display/cameramodule.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/cameramodule.cpp.s
.PHONY : src/Display/cameramodule.cpp.s

src/Display/display.o: src/Display/display.cpp.o

.PHONY : src/Display/display.o

# target to build an object file
src/Display/display.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/display.cpp.o
.PHONY : src/Display/display.cpp.o

src/Display/display.i: src/Display/display.cpp.i

.PHONY : src/Display/display.i

# target to preprocess a source file
src/Display/display.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/display.cpp.i
.PHONY : src/Display/display.cpp.i

src/Display/display.s: src/Display/display.cpp.s

.PHONY : src/Display/display.s

# target to generate assembly for a file
src/Display/display.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/display.cpp.s
.PHONY : src/Display/display.cpp.s

src/Display/inputmodule.o: src/Display/inputmodule.cpp.o

.PHONY : src/Display/inputmodule.o

# target to build an object file
src/Display/inputmodule.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/inputmodule.cpp.o
.PHONY : src/Display/inputmodule.cpp.o

src/Display/inputmodule.i: src/Display/inputmodule.cpp.i

.PHONY : src/Display/inputmodule.i

# target to preprocess a source file
src/Display/inputmodule.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/inputmodule.cpp.i
.PHONY : src/Display/inputmodule.cpp.i

src/Display/inputmodule.s: src/Display/inputmodule.cpp.s

.PHONY : src/Display/inputmodule.s

# target to generate assembly for a file
src/Display/inputmodule.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Display/inputmodule.cpp.s
.PHONY : src/Display/inputmodule.cpp.s

src/Model/Assimp/assimploader.o: src/Model/Assimp/assimploader.cpp.o

.PHONY : src/Model/Assimp/assimploader.o

# target to build an object file
src/Model/Assimp/assimploader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Assimp/assimploader.cpp.o
.PHONY : src/Model/Assimp/assimploader.cpp.o

src/Model/Assimp/assimploader.i: src/Model/Assimp/assimploader.cpp.i

.PHONY : src/Model/Assimp/assimploader.i

# target to preprocess a source file
src/Model/Assimp/assimploader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Assimp/assimploader.cpp.i
.PHONY : src/Model/Assimp/assimploader.cpp.i

src/Model/Assimp/assimploader.s: src/Model/Assimp/assimploader.cpp.s

.PHONY : src/Model/Assimp/assimploader.s

# target to generate assembly for a file
src/Model/Assimp/assimploader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Assimp/assimploader.cpp.s
.PHONY : src/Model/Assimp/assimploader.cpp.s

src/Model/Shader/shader.o: src/Model/Shader/shader.cpp.o

.PHONY : src/Model/Shader/shader.o

# target to build an object file
src/Model/Shader/shader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Shader/shader.cpp.o
.PHONY : src/Model/Shader/shader.cpp.o

src/Model/Shader/shader.i: src/Model/Shader/shader.cpp.i

.PHONY : src/Model/Shader/shader.i

# target to preprocess a source file
src/Model/Shader/shader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Shader/shader.cpp.i
.PHONY : src/Model/Shader/shader.cpp.i

src/Model/Shader/shader.s: src/Model/Shader/shader.cpp.s

.PHONY : src/Model/Shader/shader.s

# target to generate assembly for a file
src/Model/Shader/shader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Shader/shader.cpp.s
.PHONY : src/Model/Shader/shader.cpp.s

src/Model/Sprite/sprite.o: src/Model/Sprite/sprite.cpp.o

.PHONY : src/Model/Sprite/sprite.o

# target to build an object file
src/Model/Sprite/sprite.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Sprite/sprite.cpp.o
.PHONY : src/Model/Sprite/sprite.cpp.o

src/Model/Sprite/sprite.i: src/Model/Sprite/sprite.cpp.i

.PHONY : src/Model/Sprite/sprite.i

# target to preprocess a source file
src/Model/Sprite/sprite.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Sprite/sprite.cpp.i
.PHONY : src/Model/Sprite/sprite.cpp.i

src/Model/Sprite/sprite.s: src/Model/Sprite/sprite.cpp.s

.PHONY : src/Model/Sprite/sprite.s

# target to generate assembly for a file
src/Model/Sprite/sprite.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/Sprite/sprite.cpp.s
.PHONY : src/Model/Sprite/sprite.cpp.s

src/Model/renderchain.o: src/Model/renderchain.cpp.o

.PHONY : src/Model/renderchain.o

# target to build an object file
src/Model/renderchain.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/renderchain.cpp.o
.PHONY : src/Model/renderchain.cpp.o

src/Model/renderchain.i: src/Model/renderchain.cpp.i

.PHONY : src/Model/renderchain.i

# target to preprocess a source file
src/Model/renderchain.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/renderchain.cpp.i
.PHONY : src/Model/renderchain.cpp.i

src/Model/renderchain.s: src/Model/renderchain.cpp.s

.PHONY : src/Model/renderchain.s

# target to generate assembly for a file
src/Model/renderchain.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/renderchain.cpp.s
.PHONY : src/Model/renderchain.cpp.s

src/Model/renderobject.o: src/Model/renderobject.cpp.o

.PHONY : src/Model/renderobject.o

# target to build an object file
src/Model/renderobject.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/renderobject.cpp.o
.PHONY : src/Model/renderobject.cpp.o

src/Model/renderobject.i: src/Model/renderobject.cpp.i

.PHONY : src/Model/renderobject.i

# target to preprocess a source file
src/Model/renderobject.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/renderobject.cpp.i
.PHONY : src/Model/renderobject.cpp.i

src/Model/renderobject.s: src/Model/renderobject.cpp.s

.PHONY : src/Model/renderobject.s

# target to generate assembly for a file
src/Model/renderobject.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/renderobject.cpp.s
.PHONY : src/Model/renderobject.cpp.s

src/Model/testObject.o: src/Model/testObject.cpp.o

.PHONY : src/Model/testObject.o

# target to build an object file
src/Model/testObject.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/testObject.cpp.o
.PHONY : src/Model/testObject.cpp.o

src/Model/testObject.i: src/Model/testObject.cpp.i

.PHONY : src/Model/testObject.i

# target to preprocess a source file
src/Model/testObject.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/testObject.cpp.i
.PHONY : src/Model/testObject.cpp.i

src/Model/testObject.s: src/Model/testObject.cpp.s

.PHONY : src/Model/testObject.s

# target to generate assembly for a file
src/Model/testObject.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Model/testObject.cpp.s
.PHONY : src/Model/testObject.cpp.s

src/Utilities/utilities.o: src/Utilities/utilities.cpp.o

.PHONY : src/Utilities/utilities.o

# target to build an object file
src/Utilities/utilities.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Utilities/utilities.cpp.o
.PHONY : src/Utilities/utilities.cpp.o

src/Utilities/utilities.i: src/Utilities/utilities.cpp.i

.PHONY : src/Utilities/utilities.i

# target to preprocess a source file
src/Utilities/utilities.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Utilities/utilities.cpp.i
.PHONY : src/Utilities/utilities.cpp.i

src/Utilities/utilities.s: src/Utilities/utilities.cpp.s

.PHONY : src/Utilities/utilities.s

# target to generate assembly for a file
src/Utilities/utilities.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/Utilities/utilities.cpp.s
.PHONY : src/Utilities/utilities.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OpenGL"
	@echo "... src/Core/glapi.o"
	@echo "... src/Core/glapi.i"
	@echo "... src/Core/glapi.s"
	@echo "... src/Core/openGL.o"
	@echo "... src/Core/openGL.i"
	@echo "... src/Core/openGL.s"
	@echo "... src/Display/cameramodule.o"
	@echo "... src/Display/cameramodule.i"
	@echo "... src/Display/cameramodule.s"
	@echo "... src/Display/display.o"
	@echo "... src/Display/display.i"
	@echo "... src/Display/display.s"
	@echo "... src/Display/inputmodule.o"
	@echo "... src/Display/inputmodule.i"
	@echo "... src/Display/inputmodule.s"
	@echo "... src/Model/Assimp/assimploader.o"
	@echo "... src/Model/Assimp/assimploader.i"
	@echo "... src/Model/Assimp/assimploader.s"
	@echo "... src/Model/Shader/shader.o"
	@echo "... src/Model/Shader/shader.i"
	@echo "... src/Model/Shader/shader.s"
	@echo "... src/Model/Sprite/sprite.o"
	@echo "... src/Model/Sprite/sprite.i"
	@echo "... src/Model/Sprite/sprite.s"
	@echo "... src/Model/renderchain.o"
	@echo "... src/Model/renderchain.i"
	@echo "... src/Model/renderchain.s"
	@echo "... src/Model/renderobject.o"
	@echo "... src/Model/renderobject.i"
	@echo "... src/Model/renderobject.s"
	@echo "... src/Model/testObject.o"
	@echo "... src/Model/testObject.i"
	@echo "... src/Model/testObject.s"
	@echo "... src/Utilities/utilities.o"
	@echo "... src/Utilities/utilities.i"
	@echo "... src/Utilities/utilities.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

