# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nprat/Documents/OpenGL-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nprat/Documents/OpenGL-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nprat/Documents/OpenGL-Project/CMakeFiles /home/nprat/Documents/OpenGL-Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nprat/Documents/OpenGL-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGL

# Build rule for target.
OpenGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGL
.PHONY : OpenGL

# fast build rule for target.
OpenGL/fast:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/build
.PHONY : OpenGL/fast

Display/cameramodule.o: Display/cameramodule.cpp.o

.PHONY : Display/cameramodule.o

# target to build an object file
Display/cameramodule.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/cameramodule.cpp.o
.PHONY : Display/cameramodule.cpp.o

Display/cameramodule.i: Display/cameramodule.cpp.i

.PHONY : Display/cameramodule.i

# target to preprocess a source file
Display/cameramodule.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/cameramodule.cpp.i
.PHONY : Display/cameramodule.cpp.i

Display/cameramodule.s: Display/cameramodule.cpp.s

.PHONY : Display/cameramodule.s

# target to generate assembly for a file
Display/cameramodule.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/cameramodule.cpp.s
.PHONY : Display/cameramodule.cpp.s

Display/display.o: Display/display.cpp.o

.PHONY : Display/display.o

# target to build an object file
Display/display.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/display.cpp.o
.PHONY : Display/display.cpp.o

Display/display.i: Display/display.cpp.i

.PHONY : Display/display.i

# target to preprocess a source file
Display/display.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/display.cpp.i
.PHONY : Display/display.cpp.i

Display/display.s: Display/display.cpp.s

.PHONY : Display/display.s

# target to generate assembly for a file
Display/display.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/display.cpp.s
.PHONY : Display/display.cpp.s

Display/inputmodule.o: Display/inputmodule.cpp.o

.PHONY : Display/inputmodule.o

# target to build an object file
Display/inputmodule.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/inputmodule.cpp.o
.PHONY : Display/inputmodule.cpp.o

Display/inputmodule.i: Display/inputmodule.cpp.i

.PHONY : Display/inputmodule.i

# target to preprocess a source file
Display/inputmodule.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/inputmodule.cpp.i
.PHONY : Display/inputmodule.cpp.i

Display/inputmodule.s: Display/inputmodule.cpp.s

.PHONY : Display/inputmodule.s

# target to generate assembly for a file
Display/inputmodule.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Display/inputmodule.cpp.s
.PHONY : Display/inputmodule.cpp.s

Model/Assimp/assimploader.o: Model/Assimp/assimploader.cpp.o

.PHONY : Model/Assimp/assimploader.o

# target to build an object file
Model/Assimp/assimploader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Assimp/assimploader.cpp.o
.PHONY : Model/Assimp/assimploader.cpp.o

Model/Assimp/assimploader.i: Model/Assimp/assimploader.cpp.i

.PHONY : Model/Assimp/assimploader.i

# target to preprocess a source file
Model/Assimp/assimploader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Assimp/assimploader.cpp.i
.PHONY : Model/Assimp/assimploader.cpp.i

Model/Assimp/assimploader.s: Model/Assimp/assimploader.cpp.s

.PHONY : Model/Assimp/assimploader.s

# target to generate assembly for a file
Model/Assimp/assimploader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Assimp/assimploader.cpp.s
.PHONY : Model/Assimp/assimploader.cpp.s

Model/Shader/shader.o: Model/Shader/shader.cpp.o

.PHONY : Model/Shader/shader.o

# target to build an object file
Model/Shader/shader.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Shader/shader.cpp.o
.PHONY : Model/Shader/shader.cpp.o

Model/Shader/shader.i: Model/Shader/shader.cpp.i

.PHONY : Model/Shader/shader.i

# target to preprocess a source file
Model/Shader/shader.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Shader/shader.cpp.i
.PHONY : Model/Shader/shader.cpp.i

Model/Shader/shader.s: Model/Shader/shader.cpp.s

.PHONY : Model/Shader/shader.s

# target to generate assembly for a file
Model/Shader/shader.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Shader/shader.cpp.s
.PHONY : Model/Shader/shader.cpp.s

Model/Sprite/sprite.o: Model/Sprite/sprite.cpp.o

.PHONY : Model/Sprite/sprite.o

# target to build an object file
Model/Sprite/sprite.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Sprite/sprite.cpp.o
.PHONY : Model/Sprite/sprite.cpp.o

Model/Sprite/sprite.i: Model/Sprite/sprite.cpp.i

.PHONY : Model/Sprite/sprite.i

# target to preprocess a source file
Model/Sprite/sprite.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Sprite/sprite.cpp.i
.PHONY : Model/Sprite/sprite.cpp.i

Model/Sprite/sprite.s: Model/Sprite/sprite.cpp.s

.PHONY : Model/Sprite/sprite.s

# target to generate assembly for a file
Model/Sprite/sprite.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/Sprite/sprite.cpp.s
.PHONY : Model/Sprite/sprite.cpp.s

Model/renderchain.o: Model/renderchain.cpp.o

.PHONY : Model/renderchain.o

# target to build an object file
Model/renderchain.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/renderchain.cpp.o
.PHONY : Model/renderchain.cpp.o

Model/renderchain.i: Model/renderchain.cpp.i

.PHONY : Model/renderchain.i

# target to preprocess a source file
Model/renderchain.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/renderchain.cpp.i
.PHONY : Model/renderchain.cpp.i

Model/renderchain.s: Model/renderchain.cpp.s

.PHONY : Model/renderchain.s

# target to generate assembly for a file
Model/renderchain.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/renderchain.cpp.s
.PHONY : Model/renderchain.cpp.s

Model/renderobject.o: Model/renderobject.cpp.o

.PHONY : Model/renderobject.o

# target to build an object file
Model/renderobject.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/renderobject.cpp.o
.PHONY : Model/renderobject.cpp.o

Model/renderobject.i: Model/renderobject.cpp.i

.PHONY : Model/renderobject.i

# target to preprocess a source file
Model/renderobject.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/renderobject.cpp.i
.PHONY : Model/renderobject.cpp.i

Model/renderobject.s: Model/renderobject.cpp.s

.PHONY : Model/renderobject.s

# target to generate assembly for a file
Model/renderobject.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/renderobject.cpp.s
.PHONY : Model/renderobject.cpp.s

Model/testObject.o: Model/testObject.cpp.o

.PHONY : Model/testObject.o

# target to build an object file
Model/testObject.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/testObject.cpp.o
.PHONY : Model/testObject.cpp.o

Model/testObject.i: Model/testObject.cpp.i

.PHONY : Model/testObject.i

# target to preprocess a source file
Model/testObject.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/testObject.cpp.i
.PHONY : Model/testObject.cpp.i

Model/testObject.s: Model/testObject.cpp.s

.PHONY : Model/testObject.s

# target to generate assembly for a file
Model/testObject.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/Model/testObject.cpp.s
.PHONY : Model/testObject.cpp.s

OpenGL/glapi.o: OpenGL/glapi.cpp.o

.PHONY : OpenGL/glapi.o

# target to build an object file
OpenGL/glapi.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/OpenGL/glapi.cpp.o
.PHONY : OpenGL/glapi.cpp.o

OpenGL/glapi.i: OpenGL/glapi.cpp.i

.PHONY : OpenGL/glapi.i

# target to preprocess a source file
OpenGL/glapi.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/OpenGL/glapi.cpp.i
.PHONY : OpenGL/glapi.cpp.i

OpenGL/glapi.s: OpenGL/glapi.cpp.s

.PHONY : OpenGL/glapi.s

# target to generate assembly for a file
OpenGL/glapi.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/OpenGL/glapi.cpp.s
.PHONY : OpenGL/glapi.cpp.s

OpenGL/openGL.o: OpenGL/openGL.cpp.o

.PHONY : OpenGL/openGL.o

# target to build an object file
OpenGL/openGL.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/OpenGL/openGL.cpp.o
.PHONY : OpenGL/openGL.cpp.o

OpenGL/openGL.i: OpenGL/openGL.cpp.i

.PHONY : OpenGL/openGL.i

# target to preprocess a source file
OpenGL/openGL.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/OpenGL/openGL.cpp.i
.PHONY : OpenGL/openGL.cpp.i

OpenGL/openGL.s: OpenGL/openGL.cpp.s

.PHONY : OpenGL/openGL.s

# target to generate assembly for a file
OpenGL/openGL.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/OpenGL/openGL.cpp.s
.PHONY : OpenGL/openGL.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGL.dir/build.make CMakeFiles/OpenGL.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OpenGL"
	@echo "... Display/cameramodule.o"
	@echo "... Display/cameramodule.i"
	@echo "... Display/cameramodule.s"
	@echo "... Display/display.o"
	@echo "... Display/display.i"
	@echo "... Display/display.s"
	@echo "... Display/inputmodule.o"
	@echo "... Display/inputmodule.i"
	@echo "... Display/inputmodule.s"
	@echo "... Model/Assimp/assimploader.o"
	@echo "... Model/Assimp/assimploader.i"
	@echo "... Model/Assimp/assimploader.s"
	@echo "... Model/Shader/shader.o"
	@echo "... Model/Shader/shader.i"
	@echo "... Model/Shader/shader.s"
	@echo "... Model/Sprite/sprite.o"
	@echo "... Model/Sprite/sprite.i"
	@echo "... Model/Sprite/sprite.s"
	@echo "... Model/renderchain.o"
	@echo "... Model/renderchain.i"
	@echo "... Model/renderchain.s"
	@echo "... Model/renderobject.o"
	@echo "... Model/renderobject.i"
	@echo "... Model/renderobject.s"
	@echo "... Model/testObject.o"
	@echo "... Model/testObject.i"
	@echo "... Model/testObject.s"
	@echo "... OpenGL/glapi.o"
	@echo "... OpenGL/glapi.i"
	@echo "... OpenGL/glapi.s"
	@echo "... OpenGL/openGL.o"
	@echo "... OpenGL/openGL.i"
	@echo "... OpenGL/openGL.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

